# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'demo-angular-app2:$(build.buildId)'
  docuid: 'angularcontainer'
  docpwd: '0lvQNQ/MdsalZ5I0DjMwHzrllIV51R9D'

steps:
- script: docker build -f Dockerfile -t $(docuid).azurecr.io/$(imageName) .
  displayName: 'docker build'
- script: docker login -u "$(docuid)" -p "$(docpwd)" $(docuid).azurecr.io
  displayName: 'docker login to azure registry'
- script: docker push $(docuid).azurecr.io/$(imageName)
  displayName: 'docker push imagees'